/**
 * Stable, machine-readable error codes returned in every error envelope
 * as `error.code`. The mobile client should switch on these — never on
 * `error.message`, which is human-readable and may change wording.
 *
 * Convention: `DOMAIN_REASON`, SCREAMING_SNAKE_CASE, never renumbered or
 * removed once shipped (only appended to) since the mobile app persists
 * behaviour keyed off these strings.
 */
export enum ErrorCode {
  // Generic (000x)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_KEY_MISSING = 'IDEMPOTENCY_KEY_MISSING',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Auth
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
  TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',
  SESSION_REVOKED = 'AUTH_SESSION_REVOKED',
  OTP_INVALID = 'AUTH_OTP_INVALID',
  OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  OTP_MAX_ATTEMPTS_EXCEEDED = 'AUTH_OTP_MAX_ATTEMPTS_EXCEEDED',
  PIN_INVALID = 'AUTH_PIN_INVALID',
  PIN_LOCKED = 'AUTH_PIN_LOCKED',
  PIN_NOT_SET = 'AUTH_PIN_NOT_SET',

  // KYC — user-facing
  KYC_NOT_SUBMITTED = 'KYC_NOT_SUBMITTED',
  KYC_ALREADY_APPROVED = 'KYC_ALREADY_APPROVED',
  KYC_PENDING_REVIEW = 'KYC_PENDING_REVIEW',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_REQUIRED_FOR_ACTION = 'KYC_REQUIRED_FOR_ACTION',

  // KYC — admin / broker dashboard (Kusata API contract)
  KYC_ALREADY_REVIEWED = 'ALREADY_REVIEWED',
  KYC_REASON_REQUIRED = 'REASON_REQUIRED',
  KYC_NOTES_TOO_LONG = 'NOTES_TOO_LONG',
  KYC_DOCUMENTS_REQUIRED = 'DOCUMENTS_REQUIRED',
  KYC_INVALID_DOCUMENT_SLOT = 'INVALID_DOCUMENT_SLOT',
  KYC_INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  KYC_APPLICATION_NOT_FOUND = 'APPLICATION_NOT_FOUND',
  KYC_MESSAGE_TOO_LONG = 'MESSAGE_TOO_LONG',

  // Wallet / Ledger
  INSUFFICIENT_FUNDS = 'WALLET_INSUFFICIENT_FUNDS',
  WALLET_FROZEN = 'WALLET_FROZEN',
  DEPOSIT_LIMIT_EXCEEDED = 'WALLET_DEPOSIT_LIMIT_EXCEEDED',
  WITHDRAWAL_LIMIT_EXCEEDED = 'WALLET_WITHDRAWAL_LIMIT_EXCEEDED',
  VELOCITY_LIMIT_EXCEEDED = 'WALLET_VELOCITY_LIMIT_EXCEEDED',

  // Trading
  MARKET_CLOSED = 'TRADING_MARKET_CLOSED',
  INVALID_ORDER = 'TRADING_INVALID_ORDER',
  INSUFFICIENT_HOLDINGS = 'TRADING_INSUFFICIENT_HOLDINGS',
  ORDER_NOT_CANCELLABLE = 'TRADING_ORDER_NOT_CANCELLABLE',

  // Payments
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',

  // Fraud / Risk
  SUSPICIOUS_ACTIVITY_FLAGGED = 'FRAUD_SUSPICIOUS_ACTIVITY_FLAGGED',
  DEVICE_NOT_TRUSTED = 'FRAUD_DEVICE_NOT_TRUSTED',
}
